import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#485260",
        "on-secondary": "#f7f9ff",
        "outline-variant": "#abb3b7",
        "secondary-dim": "#4a5462",
        "surface-container-lowest": "#ffffff",
        "tertiary-dim": "#53506b",
        "on-background": "#2b3437",
        "surface": "#f8f9fa",
        "primary-fixed-dim": "#ced4e9",
        "error-container": "#fe8983",
        "on-primary-fixed-variant": "#545b6d",
        "background": "#f8f9fa",
        "outline": "#737c7f",
        "on-error": "#fff7f6",
        "on-tertiary": "#fcf7ff",
        "tertiary-container": "#d3ceef",
        "surface-container-high": "#e2e9ec",
        "surface-container-highest": "#dbe4e7",
        "inverse-surface": "#0c0f10",
        "surface-tint": "#575e70",
        "on-tertiary-fixed": "#34314b",
        "secondary": "#56606e",
        "primary-dim": "#4b5264",
        "on-secondary-fixed-variant": "#525c6a",
        "on-primary-fixed": "#383f50",
        "on-tertiary-fixed-variant": "#514d69",
        "surface-bright": "#f8f9fa",
        "surface-variant": "#dbe4e7",
        "surface-container": "#eaeff1",
        "surface-container-low": "#f1f4f6",
        "surface-dim": "#d1dce0",
        "on-primary": "#f7f7ff",
        "inverse-on-surface": "#9b9d9e",
        "on-primary-container": "#4b5263",
        "tertiary": "#5f5c78",
        "secondary-container": "#d9e3f4",
        "secondary-fixed-dim": "#cbd5e6",
        "on-tertiary-container": "#47445f",
        "on-surface": "#2b3437",
        "error": "#9f403d",
        "on-secondary-fixed": "#36404d",
        "primary": "#575e70",
        "on-error-container": "#752121",
        "primary-fixed": "#dce2f7",
        "on-surface-variant": "#586064",
        "primary-container": "#dce2f7",
        "tertiary-fixed": "#d3ceef",
        "secondary-fixed": "#d9e3f4",
        "error-dim": "#4e0309",
        "tertiary-fixed-dim": "#c5c0e0",
        "inverse-primary": "#d9dff5",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
} satisfies Config;
